version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DATABASE_URL=sqlite:///./exoplanet_hunter.db
    volumes:
      - ./backend:/app
      - ./data:/app/data
      - ./ml_models:/app/ml_models
    depends_on:
      - db
    restart: unless-stopped

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped

  # Database (PostgreSQL)
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=exoplanet_hunter
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Jupyter Notebooks for ML
  ml-notebooks:
    build:
      context: ./ml_models
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./ml_models:/home/jovyan/work
      - ./data:/home/jovyan/work/data
    environment:
      - JUPYTER_ENABLE_LAB=yes
    restart: unless-stopped

volumes:
  postgres_data:

